# TODO: these helper commands may be useful for the deploy script(s)
#
# ACCOUNT_NAME="test-acct"
# 
# create-account:
# 	@sncast account create --name $(ACCOUNT_NAME)
# 
# deploy-account:
# 	@sncast account deploy --name $(ACCOUNT_NAME)

run-script:
	@cd ./scripts && sncast script run $(NAME)
