#!/usr/bin/env bash

# build test binaries
# accepts a single space separated argument of the folders to build

set -ex

# get this scripts directory
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

cd "$SCRIPT_DIR"/../../ || exit 1

# integration prep
make test-integration-prep

INTEGRATION_TEST_DIR="$SCRIPT_DIR"/../
cd "$INTEGRATION_TEST_DIR" || exit 1

# parse out quotes if they exist in the string
temp="${1%\"}"
tosplit="${temp#\"}"

# find the suite name
OIFS=$IFS
IFS=' '
for x in $tosplit
do
    cd "$INTEGRATION_TEST_DIR"/"${x}" || exit 1
    go test -c ./
done
IFS=$OIFS
