// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	big "math/big"

	mock "github.com/stretchr/testify/mock"
)

// KeyGetter is an autogenerated mock type for the KeyGetter type
type KeyGetter struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *KeyGetter) Get(id string) (*big.Int, error) {
	ret := _m.Called(id)

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*big.Int, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *big.Int); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewKeyGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewKeyGetter creates a new instance of KeyGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewKeyGetter(t mockConstructorTestingTNewKeyGetter) *KeyGetter {
	mock := &KeyGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
