apiVersion: v1
kind: Service
metadata:
  name: starknet-dev-service
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
  selector:
    release: {{ .Release.Name }}
    app: starknet-dev