import { CONTRACT_LIST } from './contracts'

export const CATEGORIES = {
  SEQUENCER_UPTIME_FEED: CONTRACT_LIST.SEQUENCER_UPTIME_FEED,
  STARKNET_VALIDATOR: CONTRACT_LIST.STARKNET_VALIDATOR,
  L1_ACCESS_CONTROLLER: 'l1_access_controller',
  L1_MOCK_AGGREGATOR: 'l1_mock_aggregator',
}
