name: Build Test Image
description: A composite action that allows building and publishing the test remote runner image

inputs:
  tag:
    description: The tag to use by default and to use for checking image existance
    default: ${{ github.sha }}
    required: false
  other_tags:
    description: Other tags to push if needed
    required: false
  QA_AWS_ROLE_TO_ASSUME:
    description: The AWS role to assume as the CD user, if any. Used in configuring the docker/login-action
    required: true
  QA_AWS_REGION:
    description: The AWS region the ECR repository is located in, should only be needed for public ECR repositories, used in configuring docker/login-action
    required: true
  QA_AWS_ACCOUNT_NUMBER:
    description: The AWS region the ECR repository is located in, should only be needed for public ECR repositories, used in configuring docker/login-action
    required: true

runs:
  using: composite
  steps:
    - name: Install Cairo
      uses: ./.github/actions/install-cairo
    - name: Check if image exists
      id: check-image
      uses: smartcontractkit/chainlink-github-actions/docker/image-exists@8489879838862929f43f7d7cd1b33903965cf507 # v2.1.6
      with:
        repository: chainlink-starknet-tests
        tag: ${{ inputs.tag }}
        AWS_REGION: ${{ inputs.QA_AWS_REGION }}
        AWS_ROLE_TO_ASSUME: ${{ inputs.QA_AWS_ROLE_TO_ASSUME }}
    - name: Build and Publish Test Runner
      if: steps.check-image.outputs.exists == 'false'
      uses: smartcontractkit/chainlink-github-actions/docker/build-push@8489879838862929f43f7d7cd1b33903965cf507 # v2.1.6
      with:
        tags: |
          ${{ inputs.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ inputs.QA_AWS_REGION }}.amazonaws.com/chainlink-starknet-tests:${{ inputs.tag }}
          ${{ inputs.other_tags }}
        file: ./integration-tests/test.Dockerfile
        build-args: |
          SUITES="smoke soak"
        AWS_REGION: ${{ inputs.QA_AWS_REGION }}
        AWS_ROLE_TO_ASSUME: ${{ inputs.QA_AWS_ROLE_TO_ASSUME }}
    - name: Print Image Built
      env:
        INPUTS_TAG: ${{ inputs.tag }}
      shell: sh
      run: |
        echo "### chainlink-starknet-tests image tag for this test run :ship:" >> $GITHUB_STEP_SUMMARY
        echo "\`${INPUTS_TAG}\`" >> $GITHUB_STEP_SUMMARY
