name: Starknet Relayer Release

on:
  workflow_dispatch:

jobs:
  starknet-relayer-release:
    name: Release Starknet Relayer
    runs-on: ubuntu-latest
    steps:
      # Checkout this repository
      - name: Checkout Repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      # Store starknet version
      - name: Set Env Variables
        run: echo "STARKNET_RELAYER=$(npm info @chainlink/starknet-relayer version)" >> $GITHUB_ENV
      # Release code under vX.X.X
      - name: Release Code
        uses: softprops/action-gh-release@v1
        with:
          tag_name: relayer/v${{ env.STARKNET_RELAYER }}
          token: ${{ secrets.GITHUB_TOKEN }}
