name: Starknet Gauntlet CLI Release

on:
  workflow_dispatch:

jobs:
  starknet-gauntlet-cli-release:
    name: Starknet Gauntlet CLI Release
    runs-on: ubuntu-latest
    steps:
      # Checkout this repository
      - name: Checkout Repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      # Install nix
      - name: Install Nix
        uses: cachix/install-nix-action@d64e0553100205688c0fb2fa16edb0fc8663c590 # v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      # Install dependencies using yarn
      - name: Install Dependencies
        run: nix develop -c yarn install --frozen-lockfile
      # Build gauntlet binary
      - name: Build Gauntlet
        run: nix develop -c yarn bundle
      # Store gauntlet-cli version
      - name: Set Env Variables
        run: echo "STARKNET_GAUNTLET_CLI=$(npm info @chainlink/starknet-gauntlet-cli version)" >> $GITHUB_ENV
      # Upload gauntlet binary to gauntlet-cli release
      - name: Upload Gauntlet Binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/chainlink-starknet-*
          file_glob: true
          tag: |
            @chainlink/starknet-gauntlet-cli@${{ env.STARKNET_GAUNTLET_CLI }}
          overwrite: false
