name: Starknet Release

on:
  push:
    tags:
      - "@chainlink/starknet@[0-9]+.[0-9]+.[0-9]"

jobs:
  starknet-release:
    name: Release Starknet
    runs-on: ubuntu-latest
    steps:
      # Checkout this repository
      - name: Checkout Repo
        uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb # v2.4.1
      # Store starknet version
      - name: Set Env Variables
        run: echo "STARKNET=$(npm info @chainlink/starknet version)" >> $GITHUB_ENV
      # Release code under vX.X.X
      - name: Release Code
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{env.STARKNET}}
