name: Starknet Relayer Release

on:
  workflow_dispatch:

jobs:
  starknet-relayer-release:
    name: Release Starknet Relayer
    runs-on: ubuntu-latest
    steps:
      # Checkout this repository
      - name: Checkout Repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      # Store starknet version
      - name: Set Env Variables
        run: echo "STARKNET_RELAYER=$(npm info @chainlink/starknet-relayer version)" >> $GITHUB_ENV
      # Check if release tag exists
      - name: Check release tag
        uses: mukunku/tag-exists-action@5dfe2bf779fe5259360bb10b2041676713dcc8a3 # v1.1.0
        id: checkTag
        with:
          tag: relayer/v${{ env.STARKNET_RELAYER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Release code under vX.X.X
      - name: Release Code
        if: steps.checkTag.outputs.exists == 'false'
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          tag_name: relayer/v${{ env.STARKNET_RELAYER }}
          token: ${{ secrets.GITHUB_TOKEN }}
