name: Install Starknet Foundry (snforge and sncast)
description: A composite action that installs the snforge and sncast binaries

inputs:
  starknet_foundry_version:
    description: Starknet Foundry release version
    default: "0.27.0"
    required: false

runs:
  using: composite
  steps:
    - name: Setup Starknet Foundry for Linux
      id: install-starknet-foundry
      shell: bash
      run: |
        asdf plugin add starknet-foundry
        asdf install starknet-foundry ${{ inputs.starknet_foundry_version }}
        snforge clean-cache
        echo "/home/runner/.local/bin" >> $GITHUB_PATH
        # curl -L https://raw.githubusercontent.com/foundry-rs/starknet-foundry/master/scripts/install.sh | sh 
        # snfoundryup -v ${{ inputs.starknet_foundry_version }}
