name: Amarna Analysis
on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Amarna
        uses: crytic/amarna-action@v0.1.1
        id: amarna
        continue-on-error: true
        with:
          amarna-args: --disable-inline --exclude-rules=must-check-caller-address
          sarif: results.sarif
          target: 'contracts/src/chainlink/cairo/'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.amarna.outputs.sarif }}
          checkout_path: '/github/workspace'
