name: Example Contracts

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  run_examples_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Install Nix
        uses: cachix/install-nix-action@29bd9290ef037a3ecbdafe83cbd2185e9dd0fa0a # v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Cairo
        uses: ./.github/actions/install-cairo

      - name: Install Starknet Foundry
        uses: ./.github/actions/install-starknet-foundry

      - name: Test
        run: nix develop -c make test-examples
