name: Example Contracts

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  run_examples_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install Nix
        uses: cachix/install-nix-action@3715ab1a11cac9e991980d7b4a28d80c7ebdd8f9 # nix:v2.24.6
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Cairo
        uses: ./.github/actions/install-cairo

      - name: Install Starknet Foundry
        uses: ./.github/actions/install-starknet-foundry

      - name: Test
        run: nix develop -c make test-examples
