name: Example Contracts

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  run_examples_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Install Nix
        uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c # v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Cairo
        uses: ./.github/actions/install-cairo

      - name: Install Starknet Foundry
        uses: ./.github/actions/install-starknet-foundry

      - name: Test
        run: nix develop -c make test-examples
