name: Integration Tests Publish
# Publish the compiled integration tests

on:
  push:
    branches:
      - develop

env:
  ECR_TAG: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink-starknet-tests:develop

jobs:
  publish-integration-test-image:
    environment: integration
    permissions:
      id-token: write
      contents: read
    name: Publish Integration Test Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup GitHub Token
        id: setup-github-token
        uses: smartcontractkit/.github/actions/setup-github-token@744f70475fb76191f29debf2d581ffc095a650a4 # setup-github-token/v1
        with:
          aws-role-arn: ${{ secrets.AWS_OIDC_CHAINLINK_READ_ONLY_TOKEN_ISSUER_ROLE_ARN }}
          aws-lambda-url: ${{ secrets.GATI_RELENG_LAMBDA_URL }}
          aws-region: ${{ secrets.QA_AWS_REGION }}
      - name: Build Image
        uses: ./.github/actions/build-test-image
        with:
          other_tags: ${{ env.ECR_TAG }}
          QA_AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
          QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
          QA_AWS_ACCOUNT_NUMBER: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}
          GITHUB_TOKEN: ${{ steps.setup-github-token.outputs.access-token }}
      - name: Notify Slack
        # Only run this notification for merge to develop failures
        if: failure() && github.event_name != 'workflow_dispatch'
        uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95 # v3.0.1
        env:
          SLACK_BOT_TOKEN: ${{ secrets.QA_SLACK_API_KEY }}
        with:
          channel-id: "#team-test-tooling-internal"
          slack-message: ":x: :mild-panic-intensifies: Publish Integration Test Image failed: \n${{ format('https://github.com/{0}/actions/runs/{1}', github.repository, github.run_id) }}\nRepository: Starknet\n${{ format('Notifying <!subteam^{0}|{0}>', secrets.GUARDIAN_SLACK_NOTIFICATION_HANDLE)}}"
